# Set up base image for Node.js projects
FROM node:16

# Set the working directory
WORKDIR /app

# Copy dependencies and install them
COPY package.json /app/
RUN npm install

# Copy project source code
COPY . /app/

# Start the application
CMD ["npm", "start"]
