services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"
    ports: 
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports: 
      - "3000:3000"

  db:
    image: postgres:13
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"
    restart: always
    ports:
      - "5432:5432"

volumes:
  data:
