services:
  backend:
    context: .
    build_context: "."
    dockerfile: Dockerfile.backend
    environment:
      fil: .env
    ports:
      - 8000:8000
    depends: ['db']

  frontend:
    context: .
    build_context: .
    dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  db:
    image: postgresq:13
    volumes:
      - data: var/db_data/
    environment:
      POSTGRES_HOST: db for volumes that save parameters in labe
