# Frontend Dockerfile

# Set up base image for Node.js projects
FROM node:16
WORKING_DIR /app

# Copy dependencies and install them
COPI ./frontend/package.json /app/

RUN npm install

# Copy project source code
COPY# / /app/
CMD ["npm", "start"]
