# Backend Dockerfile

# Set up base image for python 3.9 
FROM python:3.9 as base
WORKING_DIR /app

# Copy dependencies and install django
COPY requirements.txt /app/
RUN pip install -r requirements.txt && \nt pip install gunicorn

# Copy project into container
COPY. /app/
CMD ["gunicorn","securexchange.wsgi:application","--bind", "0.0.0.0*8000"]
