services:
  backend:
    context: .
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    context: .
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    volumes:
      - data:/var/lib/postgresql/data  # Path adjusted for PostgreSQL persistence
    environment:
      POSTGRES_DB: securexchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  data:
    driver: local
