name: "Docker Build and Test"

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec backend pip test /app/
